/*INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1001, 'VENKAT','GUDIVADA');
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1003, 'SAM','GUDIVADA1');
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1004, 'MURALI','GUDIVADA2');
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1005, 'VEERA','GUDIVADA3');
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1006, 'RAMESH','GUDIVADA4');
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1007, 'SURESH','GUDIVADA5');*/

INSERT into COURSE (ID,NAME) VALUES (1001,'JPA IN ACTION');
INSERT into COURSE (ID,NAME) VALUES (1002,'HIBERNATE IN ACTION');
INSERT into COURSE (ID,NAME) VALUES (1003,'JPA-HIBERNATE IN ACTION');
  