
  
  
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1001, 'VENKAT','GUDIVADA');
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1003, 'SAM','GUDIVADA1');
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1004, 'MURALI','GUDIVADA2');
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1005, 'VEERA','GUDIVADA3');
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1006, 'RAMESH','GUDIVADA4');
INSERT INTO PERSON (ID,NAME,LOCATION) VALUES (1007, 'SURESH','GUDIVADA5');
  